### ISSUE TITLE
Section titles not behaving correctly

### ISSUE THREAD

**Issue by joj3000** [GONZALEZD/cupertino_listview#2] opened 2021-02-05 12:51 UTC
Hey, maybe this will save you guys some time:

**Problem**: All the section titles were not behaving correctly
![1](https://user-images.githubusercontent.com/52532656/107035397-6a4ce600-67b8-11eb-958a-6015b84dd99c.gif)

**Solution:** 
```
Widget _myListView(){
  return MediaQuery.removePadding(
    context: context,
    removeTop: true,
    child: CupertinoListView.builder(
     .......
    )
  );
}
```
![1111](https://user-images.githubusercontent.com/52532656/107035685-d596b800-67b8-11eb-9d2f-4a5ddfc1c525.gif)

**Comment by GONZALEZD** [comment] 2021-02-05 16:37
Hi Joj3000,
I checked behavior using padding and margin (from Container), and SafeArea minimum (margin).
I suspected a problem with margins (used to draw shadows), but there is not graphical bug, so I'm not sure where the root bug is.

Also, I don't fully understand your design, as the sticky header "IT IS" doesn't have shadow, whereas "WHAT IT IS" has (first only top shadow, then no shadow, and finally a bottom shadow when widget becomes sticky).

I "kind of" reproduced the bug by using MediaQuery.removePadding on top of the list, which is confusing because it's the solution to your problem.


I'm happy that you found a solution, but on my side I haven't detected any problem related to draw in the library that I can fix. (it helped me to find and fix another bug related to scroll controller, so a new version will be available soon). Therefore I'm closing this issue.

Regards,
David GONZALEZ.

**Closed as completed by GONZALEZD** 2021-02-05 16:37 UTC
